name: Flask-App GitOps Pipeline
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push
      run: |
        docker build -t worldvit/flask-app:${{ github.sha }} .
        docker push worldvit/flask-app:${{ github.sha }}

    - name: Update Manifest and Push
      run: |
        sed -i "s|image: worldvit/flask-app:.*|image: worldvit/flask-app:${{ github.sha }}|g" deployment.yaml
        git config --global user.email "bot@github.com"
        git config --global user.name "github-actions[bot]"
        git add deployment.yaml
        git commit -m "chore: update image tag to ${{ github.sha }} [skip ci]"
        git push
